#! /bin/bash
monarch=~/SW/monarch/git
dasio=$monarch/libs/dasio/src
dasiosrc="$dasio/appid.cc
  $dasio/loop.cc
  $dasio/not_parsed.cc
  $dasio/server.cc
  $dasio/ascii_escape.cc
  $dasio/socket.cc
  $dasio/client.cc
  $dasio/msg.cc
  $dasio/timeout.cc
  $dasio/unix_name.cc
  $dasio/interface.cc
  $dasio/host_session.cc"

nl=$monarch/libs/nl
nlsrc="$nl/nl.h
  $nl/newmem.c
  $nl/nlresp.c
  $nl/nldbg.c
  $nl/nl_assert.h
  $nl/nl_verr.c
  $nl/nl_error.c"

oui=/usr/local/include/oui.h

srcs="BBB/*
POPS_srvr.cc
POPS_srvroui.cc
POPS_srvr.h
../../TM/services"

make POPS_srvroui.cc

dest=pops:SW/srvr
echo Creating directories
ssh pops mkdir -p /root/SW/srvr/dasio
echo Copying sources
scp $dasiosrc $nlsrc $oui $srcs $dest
echo Copying dasio headers
scp $dasio/dasio/*.h $dest/dasio
echo Done
