function pcosmidpops2d(varargin)
% pcosmidpops2d( [...] );
% POPS2 Drift
h = timeplot({'POPS2_Tdrift'}, ...
      'POPS2 Drift', ...
      'Drift', ...
      {'POPS2\_Tdrift'}, ...
      varargin{:} );
