function pcosmidtmct(varargin);
% pcosmidtmct( [...] );
% T Mbase Core T
h = timeplot({'coretemp[4]'}, ...
      'T Mbase Core T', ...
      'Core T', ...
      {'coretemp[4]'}, ...
      varargin{:} );
