function pcosmidpopshkb(varargin)
% pcosmidpopshkb( [...] );
% POPS HK Baseline
h = timeplot({'POPS_Baseline','POPS2_Baseline'}, ...
      'POPS HK Baseline', ...
      'Baseline', ...
      {'POPS\_Baseline','POPS2\_Baseline'}, ...
      varargin{:} );
