function pcosmidpops2s(varargin)
% pcosmidpops2s( [...] );
% POPS2 Surface
h = timeplot({'POPS2_Surf_Area'}, ...
      'POPS2 Surface', ...
      'Surface', ...
      {'POPS2\_Surf\_Area'}, ...
      varargin{:} );
