function pcosmidpops2_hkstale(varargin);
% pcosmidpops2_hkstale( [...] );
% POPS2 HK Stale
h = timeplot({'POPS2_Stale','POPS2_DrvStale'}, ...
      'POPS2 HK Stale', ...
      'Stale', ...
      {'POPS2\_Stale','POPS2\_DrvStale'}, ...
      varargin{:} );
