function pcosmidpops2v(varargin);
% pcosmidpops2v( [...] );
% POPS2 Volume
h = timeplot({'POPS2_Vol_Density'}, ...
      'POPS2 Volume', ...
      'Volume', ...
      {'POPS2\_Vol\_Density'}, ...
      varargin{:} );
