function pcosmidpops2_hkstd(varargin)
% pcosmidpops2_hkstd( [...] );
% POPS2 HK STD
h = timeplot({'POPS2_STD'}, ...
      'POPS2 HK STD', ...
      'STD', ...
      {'POPS2\_STD'}, ...
      varargin{:} );
