function pcosmidpopshkldm(varargin);
% pcosmidpopshkldm( [...] );
% POPS HK LD Mon
h = timeplot({'POPS_LD_Mon'}, ...
      'POPS HK LD Mon', ...
      'LD Mon', ...
      {'POPS\_LD\_Mon'}, ...
      varargin{:} );
