function pcosmidpopsr(varargin)
% pcosmidpopsr( [...] );
% POPS Raw ccs
h = timeplot({'POPS_Flow','POPS2_Flow'}, ...
      'POPS Raw ccs', ...
      'Raw ccs', ...
      {'POPS\_Flow','POPS2\_Flow'}, ...
      varargin{:} );
