function pcosmidpopspops2_bins(varargin)
% pcosmidpopspops2_bins( [...] );
% POPS POPS2 Bins
h = timeplot({'POPS2_Bin'}, ...
      'POPS POPS2 Bins', ...
      'POPS2 Bins', ...
      {'POPS2\_Bin'}, ...
      varargin{:} );
