function pcosmidtmtd(varargin);
% pcosmidtmtd( [...] );
% T Mbase T Drift
h = timeplot({'SysTDrift'}, ...
      'T Mbase T Drift', ...
      'T Drift', ...
      {'SysTDrift'}, ...
      varargin{:} );
