function pcosmidpopshkstale(varargin)
% pcosmidpopshkstale( [...] );
% POPS HK Stale
h = timeplot({'POPS_Stale','POPS_DrvStale','POPS2_Stale','POPS2_DrvStale'}, ...
      'POPS HK Stale', ...
      'Stale', ...
      {'POPS\_Stale','POPS\_DrvStale','POPS2\_Stale','POPS2\_DrvStale'}, ...
      varargin{:} );
