function pcosmidpopss(varargin)
% pcosmidpopss( [...] );
% POPS Surface
h = timeplot({'POPS_Surf_Area','POPS2_Surf_Area'}, ...
      'POPS Surface', ...
      'Surface', ...
      {'POPS\_Surf\_Area','POPS2\_Surf\_Area'}, ...
      varargin{:} );
