function pcosmidpopsf(varargin)
% pcosmidpopsf( [...] );
% POPS Flow
h = timeplot({'POPS_ccm','POPS2_ccm'}, ...
      'POPS Flow', ...
      'Flow', ...
      {'POPS\_ccm','POPS2\_ccm'}, ...
      varargin{:} );
