function pcosmidpops2r(varargin);
% pcosmidpops2r( [...] );
% POPS2 Raw ccs
h = timeplot({'POPS2_Flow'}, ...
      'POPS2 Raw ccs', ...
      'Raw ccs', ...
      {'POPS2\_Flow'}, ...
      varargin{:} );
