function pcosmidpopsd(varargin)
% pcosmidpopsd( [...] );
% POPS Drift
h = timeplot({'POPS_Tdrift','POPS2_Tdrift'}, ...
      'POPS Drift', ...
      'Drift', ...
      {'POPS\_Tdrift','POPS2\_Tdrift'}, ...
      varargin{:} );
