function pcosmidpops2num_cc(varargin);
% pcosmidpops2num_cc( [...] );
% POPS2 num cc
h = timeplot({'POPS2_num_cc'}, ...
      'POPS2 num cc', ...
      'num cc', ...
      {'POPS2\_num\_cc'}, ...
      varargin{:} );
