function pcosmidpopsp(varargin)
% pcosmidpopsp( [...] );
% POPS P
h = timeplot({'POPS_P_mbar','POPS2_P_mbar'}, ...
      'POPS P', ...
      'P', ...
      {'POPS\_P\_mbar','POPS2\_P\_mbar'}, ...
      varargin{:} );
