function pcosmidpopshks(varargin)
% pcosmidpopshks( [...] );
% POPS HK Srvr
h = timeplot({'POPS_Srvr','POPS2_Srvr'}, ...
      'POPS HK Srvr', ...
      'Srvr', ...
      {'POPS\_Srvr','POPS2\_Srvr'}, ...
      varargin{:} );
