function pcosmidpops2pn(varargin);
% pcosmidpops2pn( [...] );
% POPS2 Part Num
h = timeplot({'POPS2_Part_Num'}, ...
      'POPS2 Part Num', ...
      'Part Num', ...
      {'POPS2\_Part\_Num'}, ...
      varargin{:} );
