function pcosmidpopshkb(varargin);
% pcosmidpopshkb( [...] );
% POPS HK Baseline
h = timeplot({'POPS_Baseline'}, ...
      'POPS HK Baseline', ...
      'Baseline', ...
      {'POPS\_Baseline'}, ...
      varargin{:} );
