function pcosmidpops2_hkldt(varargin);
% pcosmidpops2_hkldt( [...] );
% POPS2 HK LD Temp
h = timeplot({'POPS2_LDTemp'}, ...
      'POPS2 HK LD Temp', ...
      'LD Temp', ...
      {'POPS2\_LDTemp'}, ...
      varargin{:} );
