function pcosmidpops2_hkb(varargin);
% pcosmidpops2_hkb( [...] );
% POPS2 HK Baseline
h = timeplot({'POPS2_Baseline'}, ...
      'POPS2 HK Baseline', ...
      'Baseline', ...
      {'POPS2\_Baseline'}, ...
      varargin{:} );
