function pcosmidpops2_hkldm(varargin);
% pcosmidpops2_hkldm( [...] );
% POPS2 HK LD Mon
h = timeplot({'POPS2_LD_Mon'}, ...
      'POPS2 HK LD Mon', ...
      'LD Mon', ...
      {'POPS2\_LD\_Mon'}, ...
      varargin{:} );
