function pcosmidpops2b(varargin);
% pcosmidpops2b( [...] );
% POPS2 Bins
h = timeplot({'POPS2_Bin[16]'}, ...
      'POPS2 Bins', ...
      'Bins', ...
      {'POPS2\_Bin[16]'}, ...
      varargin{:} );
