function pcosmidtmct(varargin);
% pcosmidtmct( [...] );
% T Mbase Core T
h = timeplot({'coretemp1','coretemp2','coretemp3','coretemp4'}, ...
      'T Mbase Core T', ...
      'Core T', ...
      {'coretemp1','coretemp2','coretemp3','coretemp4'}, ...
      varargin{:} );
