function pcosmidpops2_hks(varargin)
% pcosmidpops2_hks( [...] );
% POPS2 HK Srvr
h = timeplot({'POPS2_Srvr'}, ...
      'POPS2 HK Srvr', ...
      'Srvr', ...
      {'POPS2\_Srvr'}, ...
      varargin{:} );
