function pcosmidpopspn(varargin)
% pcosmidpopspn( [...] );
% POPS Part Num
h = timeplot({'POPS_Part_Num','POPS2_Part_Num'}, ...
      'POPS Part Num', ...
      'Part Num', ...
      {'POPS\_Part\_Num','POPS2\_Part\_Num'}, ...
      varargin{:} );
