function pcosmidpopshkstd(varargin)
% pcosmidpopshkstd( [...] );
% POPS HK STD
h = timeplot({'POPS_STD','POPS2_STD'}, ...
      'POPS HK STD', ...
      'STD', ...
      {'POPS\_STD','POPS2\_STD'}, ...
      varargin{:} );
