function pcosmidpopspopsb(varargin)
% pcosmidpopspopsb( [...] );
% POPS POPS Bins
h = timeplot({'POPS_Bin'}, ...
      'POPS POPS Bins', ...
      'POPS Bins', ...
      {'POPS\_Bin'}, ...
      varargin{:} );
