function pengpopsnum_cc(varargin);
% pengpopsnum_cc( [...] );
% POPS num cc
h = timeplot({'POPS_num_cc'}, ...
      'POPS num cc', ...
      'num cc', ...
      {'POPS\_num\_cc'}, ...
      varargin{:} );
